# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hr_management
    username: postgres
    password: admin
  # JPA properties
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  # RabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # Bean
    main:
      allow-bean-definition-overriding: true

# Port
server:
  port: 8080

# JWT key
security:
  jwt:
    secret-key: 5ro7kcegbwT9FtQ1IRTwn8HgC+yG2cLM0hTTvRyQW6dIGE8SOveaA68GoodwTjiZ217ai63O8nCxrM6m9zE0gb33hSfuHR0wyUpHTlSX3CB4cPqI4F4c65XdrIU+yIPv2sqHZphep+V7H+T7kF0dLVGbfvLlUBGZm6rAFXYynKc=
    expiration-time: 3600000

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui
